name: Goreleaser

on:
  push:
 # triggers only if push new tag version, like `0.8.4` or else
permissions:
  contents: write
  id-token: write
  packages: write
  
jobs:
  release:
    name: GoReleaser release
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
        id: go

      - name: Chocolatey 🍫📦
        run: |
          go mod download
          go generate ./...
          ./scripts/completions.sh
          ./scripts/manpages.sh
